global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_smarthost: 'smtp.gmail.com:587'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitry_baskakov'
  email_configs:
  - to: 'gamer.pvs@gmail.com'
    from : 'gamer.pvs@gmail.com'
    auth_username: 'gamer.pvs'
    auth_password: 'password'