version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:

  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - 9292:${UI_PORT}/tcp
    networks:
       - front_net
       - mon
  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - back_net
      - front_net
      - mon

  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - back_net
      - front_net
      - mon

  prometheus:
    image: ${USERNAME}/prometheus:${VERSION_PROM}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - mon

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - mon

  mongo-exporter:
    image: ${USERNAME}/mongo_exporter
    environment:
      - MONGODB_URL=mongodb://post_db
    networks:
      - mon

  cloudprober:
    image: ${USERNAME}/cloudprober
    networks:
       - front_net
       - back_net
       - mon

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
  mon:
