version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI}
    volumes:
      - ./ui:/data/ui
    ports:
      - 9292:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION_POST}
    volumes:
      - ./post:/data/post
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    volumes:
      - ./comment:/data/comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  ui:
  post:
  comment:

networks:
  back_net:
  front_net:
